### ISSUE TITLE
Master of Cruelty portuguese name not there

### ISSUE THREAD

**Issue by Dinidiniz** [scryfall/gatherer-bugs#63] opened 2020-01-15 14:02 UTC
Hi!

The card Master of Cruelty doesn't have a translation for portuguese in scryfall:
https://scryfall.com/card/dgm/82/pt/master-of-cruelties

The translation should be "Mestre das Crueldades".

**Comment by spacemonaut** [comment] 2020-01-15 20:21
duplicate of #43; the entirety of DGM experiences this for PT

**Closed by spacemonaut** 2020-01-15 20:21 UTC
